spring.application.name=pets
<<<<<<< Updated upstream
=======
spring.security.user.name=richard
spring.security.user.password=akkad
logging.level.org.springframework.security=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/pets
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
>>>>>>> Stashed changes
