spring.application.name=pets

spring.security.user.name=richard
spring.security.user.password=akkad
logging.level.org.springframework.security=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5432/pets
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.github.client-id=Ov23linG8ah468Amgtgn
spring.security.oauth2.client.registration.github.client-secret=6ff860b7146f4f168e4ba712f99699e128cb226c
spring.security.oauth2.client.registration.google.client-id=43615410122-5h0a5in1tdercig4tgfq2oqrhm4junr3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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